class Solution {
public:
    bool isPowerOfTwo(int n) {
        //BECAUSE THE POWER OF TWO WILL HAVE ONLY ONE SET BIT AND COUNT OF SET BIT IS ONE AND HENCE IT CAN BE DONE BY COUNTING THE SET BIT OR DOING AND WITH N-1 WHICH CONVERTS THE OTHER BIT TO 0 -> 1 IF ONLY ONE BIT IS SET THEN OTHER BECOME ZERO AND DOING AND WILL GIVE THE ZERO VALUE AND IF NOT THE IT IS NOT A POWER OF TWO BCZ ONLY ONE BIT SHOULD BE SET i.e 1,e.g 16=(10000),32=(100000).
        if (n <= 0)
            return false;

        return (n & (n - 1)) == 0;
    }
};
